version: '2'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d
     - /var/www:/var/www
     - /var/log/docker:/var/log/docker
    ports:
     - "8081:80"
    links:
     - php
  php:
    image: php:wenba
    volumes:
     - /var/www:/var/www
     - /var/log/docker:/data/logs
    links:
     - mysql
     - redis
    working_dir: /var/www
  redis:
    image: redis:3-alpine
    volumes:
     - /Users/yiming/lib/redis:/data
  mysql:
    image: mysql:5.6
    restart: always
    volumes:
     - ./mysql.conf:/etc/mysql/conf.d 
     - /Users/yiming/lib/mysql:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: 1a2b3c
    ports:
     - "3333:3306"
